modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="tutorial"
version="1.0"
displayName="Ruby Mod"
credits="ME!"
authors="YutyTuty"
description='''
A super shitty basic mod.
'''

[[dependencies.tutorial]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tutorial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
